runtime:
  rest:
    baseUrl: '/api'
    baseUrlSlash: '/api/'

web:
  requestDiagnostic: true
  cors:
    enabled: true
    path: '/api/*'
    properties:
      allowOrigin: '*'
      supportedMethods: GET,PUT,POST,DELETE,PATCH

rest:
  # The base path of REST resources which will prefix all resource paths
  path: /api
  # Set of Jersey features to enable
  # features:
  #  - (Class<?>)
  # The base URI used for building hypermedia params
  # baseParam: (String)
  # The base URI used for building hypermedia rel
  # baseRel: (String)
  # If true, a JSON-Home resource describing REST entry-points will be served on REST base path
  jsonHome: true
  # Allows to specify custom Jersey properties (key: property name, value: property value)
  jerseyProperties:
  # key: (String)
  # If JSP support is enabled, the path where JSP files are located
  # jspPath: (String)
  exceptionMapping:
    # If true, security exceptions are automatically mapped to adequate HTTP responses
    security: true
    # If true, all exceptions not already mapped are mapped to a 500 HTTP response
    all: true
